Repository openshift/telemeter, pull requests merged in 2018-12, with the labels that each got.

#102 Fix ca bundle used to talk to telemeter client for metrics
  jsonnet/telemeter/client/kubernetes.libsonnet
Labels: lgtm, size/XS

#103 pkg/metricfamily: lock label transformer
  pkg/metricfamily/label.go
Labels: lgtm, size/XS

#104 Add comments to each of the metrics in telemeter to explain there use
  jsonnet/telemeter/client.libsonnet
  jsonnet/telemeter/metrics.json
  jsonnet/telemeter/metrics.jsonnet
  jsonnet/telemeter/server.libsonnet
  manifests/client/serviceMonitor.yaml
  metrics.json
Labels: lgtm, size/M

#107 jsonnet: fix prometheus SAR
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/lib/list.libsonnet
  manifests/prometheus/list.yaml
Labels: lgtm, size/S

#108 docs: document the collected metrics.
  docs/data-collection.md
  docs/sample-metrics.md
Labels: lgtm, size/L

#106 jsonnet: put metrics into jsonnet format to simplify
  jsonnet/telemeter/metrics.jsonnet
Labels: lgtm, size/M

#109 jsonnet: namespace non-namespaced objects
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/lib/list.libsonnet
  manifests/prometheus/list.yaml
Labels: lgtm, size/S

#111 Makefile: create generate test
  Makefile
Labels: lgtm, size/XS

#110 Makefile,docs: embed jsonnet in docs
  Makefile
  docs/data-collection.md
Labels: lgtm, size/M
