Repository openshift/telemeter, pull requests merged in 2018-10, with the labels that each got.

#35 add service account with correct roles to telemeter-client
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/telemeter-client-clusterRole.yaml
  manifests/telemeter-client-clusterRoleBinding.yaml
  manifests/telemeter-client-deployment.yaml
  manifests/telemeter-client-serviceAccount.yaml
Labels: lgtm, size/M

#36 secure telemeter client with rbac proxy
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/telemeter-client-clusterRole.yaml
  manifests/telemeter-client-deployment.yaml
  manifests/telemeter-client-service.yaml
  manifests/telemeter-client-serviceMonitor.yaml
Labels: lgtm, size/L

#38 Add RHD credentials to deploy configs
  deploy/telemeter-server.yaml
  deploy/telemeter.secret.yaml
Labels: lgtm, size/S

#39 oidc for tollbooth
  cmd/telemeter-server/main.go
  deploy/telemeter-server.yaml
  pkg/oauth2/token_source.go
  pkg/oauth2/token_source_test.go
Labels: lgtm, size/L

#42 deploy: bump telemeter-client for api.ci
  deploy/telemeter-client-openshift.yaml
  deploy/telemeter-client.yaml
Labels: lgtm, size/XS

#44 jsonnet: cleanup telemeter client
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
Labels: lgtm, size/XS

#46 add telemeter server jsonnet
  Makefile
  jsonnet/client.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/server.jsonnet
  jsonnet/telemeter/server/.gitignore
  jsonnet/telemeter/server/jsonnetfile.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  jsonnet/telemeter/server/kubernetes/list.libsonnet
  jsonnet/telemeter/server/telemeter-server.libsonnet
  manifests/client/clusterRole.yaml
  manifests/client/clusterRoleBinding.yaml
  manifests/client/deployment.yaml
  manifests/client/secret.yaml
  manifests/client/service.yaml
  manifests/client/serviceAccount.yaml
  manifests/client/serviceMonitor.yaml
  manifests/server/list.yaml
  manifests/server/secret.yaml
  manifests/server/service.yaml
  manifests/server/serviceMonitor.yaml
  manifests/server/statefulSet.yaml
Labels: lgtm, size/XL

#43 add jsonnet for prometheus
  Makefile
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus.jsonnet
  jsonnet/telemeter/prometheus/kubernetes/kubernetes.libsonnet
  jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
  jsonnet/telemeter/prometheus/prometheus-telemeter.libsonnet
  jsonnet/telemeter/server/kubernetes/list.libsonnet
  manifests/prometheus/clusterRole.yaml
  manifests/prometheus/clusterRoleBinding.yaml
  manifests/prometheus/htpasswdSecret.yaml
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
  manifests/prometheus/proxySecret.yaml
  manifests/prometheus/roleBindingConfig.yaml
  manifests/prometheus/roleBindingSpecificNamespaces.yaml
  manifests/prometheus/roleConfig.yaml
  manifests/prometheus/roleSpecificNamespaces.yaml
  manifests/prometheus/route.yaml
  manifests/prometheus/rules.yaml
  manifests/prometheus/service.yaml
  manifests/prometheus/serviceAccount.yaml
  manifests/prometheus/serviceMonitor.yaml
Labels: lgtm, size/XL

#49 Fix gossip join parameter
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: lgtm, size/S

#50 fix two jsonnet typos
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/server/list.yaml
  manifests/server/service.yaml
Labels: lgtm, size/S

#47 telemeter refactorings
  cmd/authorization-server/main.go
  cmd/telemeter-client/main.go
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  pkg/authorize/client.go
  pkg/authorize/cluster.go
  pkg/authorize/handler.go
  pkg/authorize/jwt/claims.go
  pkg/authorize/jwt/client_authorizer.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/jwt/handler_test.go
  pkg/authorize/jwt/signer.go
  pkg/authorize/jwt/validator.go
  pkg/authorize/roundtripper.go
  pkg/authorize/stub/stub.go
  pkg/authorize/token_store.go
  pkg/authorize/tollbooth/mock.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/authorizer/authorizer.go
  pkg/authorizer/jwt/jwt.go
  pkg/authorizer/remote/types.go
  pkg/authorizer/server/doc.go
  pkg/authorizer/server/server.go
  pkg/authorizer/server/server_test.go
  pkg/authorizer/server/types.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/memberlist.go
  pkg/forwarder/forwarder.go
  pkg/http/authorizer/authorizer.go
  pkg/http/instrument.go
  pkg/http/roundtripper.go
  pkg/http/routes.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/metricfamily/all_transformer.go
  pkg/metricfamily/multi_transformer.go
  pkg/store/diskstore/diskstore.go
  pkg/store/instrumented/instrumented.go
  pkg/store/memstore/memstore.go
  pkg/store/store.go
  pkg/untrusted/untrusted.go
  pkg/validator/validator.go
Labels: lgtm, size/XXL

#52 pkg/http/server: drop metric timestamps on federate
  cmd/telemeter-server/main_test.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/metricfamily/drop_timestamp.go
  pkg/metricfamily/drop_timestamp_test.go
Labels: lgtm, size/L

#55 linting: fix issues in telemeter, add linting to CI
  .gitignore
  Makefile
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/jwt/handler_test.go
  pkg/authorize/stub/stub.go
  pkg/authorize/token_store.go
  pkg/authorize/tollbooth/mock.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/http/routes.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/metricfamily/drop_timestamp_test.go
  pkg/metricfamily/invalid.go
  pkg/metricfamily/sort.go
  pkg/metricfamily/transform_test.go
  pkg/metricsclient/metricsclient.go
  pkg/oauth2/token_source_test.go
  pkg/store/diskstore/diskstore.go
Labels: lgtm, size/L

#56 pkg/authorize: use centralized fnv hash
  pkg/authorize/stub/stub.go
  pkg/authorize/tollbooth/mock.go
  pkg/fnv/hash.go
  pkg/fnv/hash_test.go
  pkg/store/diskstore/diskstore.go
Labels: lgtm, size/L

#57 Default to url
  cmd/telemeter-client/main.go
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/secret.yaml
Labels: lgtm, size/S

#59 jsonnet: reference cluster-monitoring-view
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/clusterRole.yaml
  manifests/client/clusterRoleBindingView.yaml
Labels: lgtm, size/M

#63 jsonnet/telemeter/client: add support for salt
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/secret.yaml
Labels: lgtm, size/S

#66 Add ServiceAccount to telemeter server
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/serviceAccount.yaml
Labels: lgtm, size/S

#70 jsonnet/telemeter/server: re-add name env var
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: lgtm, size/S

#67 Adds build-deploy.sh script for CI integration
  build_deploy.sh
  dockerfiles/Dockerfile.build
  dockerfiles/Dockerfile.deploy
  dockerfiles/README.txt
Labels: lgtm, size/M

#72 jsonnet: do not render volumeClaimTemplates
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: lgtm, size/S

#64 ttl based memory store
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/store/diskstore/diskstore.go
  pkg/store/instrumented/instrumented.go
  pkg/store/memstore/memstore.go
  pkg/store/memstore/memstore_test.go
  pkg/store/store.go
Labels: lgtm, size/XL
