Repository openshift/telemeter, pull requests merged in 2018-09, with the labels that each got.

#19 cmd/telemeter-server: register handler request size metrics
  cmd/telemeter-server/main.go
  pkg/http/server/server.go
Labels: lgtm, size/S

#21 pkg/transform: rename to metricfamily, separate source files
  .gitignore
  cmd/telemeter-client/main.go
  cmd/telemeter-server/main_test.go
  pkg/cluster/cluster.go
  pkg/forwarder/forwarder.go
  pkg/http/server/diskstore.go
  pkg/http/server/memstore.go
  pkg/http/server/server.go
  pkg/metricfamily/all_transformer.go
  pkg/metricfamily/anonymize.go
  pkg/metricfamily/count.go
  pkg/metricfamily/drop_unsorted.go
  pkg/metricfamily/empty.go
  pkg/metricfamily/expired.go
  pkg/metricfamily/invalid.go
  pkg/metricfamily/label.go
  pkg/metricfamily/none.go
  pkg/metricfamily/pack.go
  pkg/metricfamily/rename.go
  pkg/metricfamily/required.go
  pkg/metricfamily/sort.go
  pkg/metricfamily/transform.go
  pkg/metricfamily/transform_test.go
  pkg/metricfamily/unsorted.go
  pkg/transform/transform.go
  pkg/untrusted/untrusted.go
Labels: lgtm, size/XXL

#22 test: fix integration test typo
  test/integration.sh
Labels: lgtm, size/XS

#23 cmd,pkg: fix some golint rules
  cmd/authorization-server/main.go
  pkg/authorizer/authorizer.go
  pkg/authorizer/server/server.go
Labels: lgtm, size/S

#25 init jsonnet and create telemeter-client libsonnet
  Makefile
  jsonnet/.gitignore
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/telemeter/client/.gitignore
  jsonnet/telemeter/client/jsonnetfile.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  jsonnet/telemeter/client/telemeter-client.libsonnet
  manifests/telemeter-client-deployment.yaml
  manifests/telemeter-client-secret.yaml
  manifests/telemeter-client-service.yaml
  manifests/telemeter-client-serviceMonitor.yaml
Labels: lgtm, size/L

#26 jsonnet: address pr 25 nits
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  jsonnet/telemeter/client/telemeter-client.libsonnet
Labels: lgtm, size/S

#28 jsonnet: put telemeter server URL into secret and env var
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/telemeter-client-deployment.yaml
  manifests/telemeter-client-secret.yaml
Labels: lgtm, size/S

#27 pkg/authorizer: adapt to tollbooth API changes
  cmd/authorization-server/main.go
  pkg/authorizer/server/server.go
  pkg/authorizer/server/server_test.go
  pkg/authorizer/server/simple.go
  pkg/authorizer/server/test.go
  pkg/authorizer/server/types.go
  test/responses.json
  test/tokens.json
Labels: lgtm, size/L

#29 jsonnet: extend jobs with telemeter client
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/telemeter-client.libsonnet
Labels: lgtm, size/XS

#30 makes telemeter-server.yaml template
  deploy/telemeter-server.yaml
Labels: lgtm, size/S

#31 deploy: set replica count to 3
  deploy/telemeter-server.yaml
Labels: lgtm, size/XS

#32 deploy: set tollbooth authorize url
  deploy/telemeter-server.yaml
Labels: lgtm, size/XS

#33 vendor: add go-oidc
  glide.lock
  glide.yaml
  vendor/github.com/coreos/go-oidc/.gitignore
  vendor/github.com/coreos/go-oidc/.travis.yml
  vendor/github.com/coreos/go-oidc/CONTRIBUTING.md
  vendor/github.com/coreos/go-oidc/DCO
  vendor/github.com/coreos/go-oidc/LICENSE
  vendor/github.com/coreos/go-oidc/MAINTAINERS
  vendor/github.com/coreos/go-oidc/NOTICE
  vendor/github.com/coreos/go-oidc/README.md
  vendor/github.com/coreos/go-oidc/code-of-conduct.md
  vendor/github.com/coreos/go-oidc/example/README.md
  vendor/github.com/coreos/go-oidc/example/idtoken/app.go
  vendor/github.com/coreos/go-oidc/example/nonce/app.go
  vendor/github.com/coreos/go-oidc/example/userinfo/app.go
  vendor/github.com/coreos/go-oidc/jose.go
  vendor/github.com/coreos/go-oidc/jwks.go
  vendor/github.com/coreos/go-oidc/jwks_test.go
  vendor/github.com/coreos/go-oidc/oidc.go
  vendor/github.com/coreos/go-oidc/oidc_test.go
  vendor/github.com/coreos/go-oidc/test
  vendor/github.com/coreos/go-oidc/verify.go
  vendor/github.com/coreos/go-oidc/verify_test.go
Labels: lgtm, size/XXL
