Repository openshift/telemeter, pull requests merged in 2018-11, with the labels that each got.

#74 jsonnet/prometheus: configure permissions
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
  jsonnet/telemeter/prometheus/prometheus-telemeter.libsonnet
  manifests/prometheus/list.yaml
Labels: lgtm, size/M

#75 *: update use of service certs ca bundle
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/servingCertsCABundle.yaml
Labels: lgtm, size/M

#77 test: Update the integration test to deal with entropy
  test/integration.sh
Labels: lgtm, size/XS

#81 name route certs secret
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/prometheus/kubernetes/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/route.yaml
Labels: lgtm, size/S

#82 pkg/cluster: consider nodes not problematic after expiration
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
Labels: lgtm, size/M

#79 rules: Gather cluster version metrics from a cluster
  deploy/default-rules
  jsonnet/telemeter/client/metrics.json
Labels: lgtm, size/S

#84 Add Configmap Reload to client
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: lgtm, size/S

#86 jsonnet/telemeter/client: fix configMap volume
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/servingCertsCABundle.yaml
Labels: lgtm, size/S

#87 pkg/authorize/jwt: fix handling of required labels
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/jwt/handler_test.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/metricfamily/multi_transformer.go
  pkg/validate/validator.go
Labels: lgtm, size/L

#88 jsonnet: use internal endpoint for telemeter servicemonitors
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/serviceMonitor.yaml
  manifests/server/serviceMonitorFederate.yaml
Labels: lgtm, size/M

#89 jsonnet: fix swapped internal/cluster ports
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/service.yaml
  manifests/server/statefulSet.yaml
Labels: lgtm, size/S

#91 jsonnet/telemeter: use TLS for telemeter server
  jsonnet/client.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus.jsonnet
  jsonnet/server.jsonnet
  jsonnet/telemeter/client.libsonnet
  jsonnet/telemeter/client/kubernetes.libsonnet
  jsonnet/telemeter/jsonnetfile.json
  jsonnet/telemeter/lib/list.libsonnet
  jsonnet/telemeter/metrics.json
  jsonnet/telemeter/prometheus.libsonnet
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/jsonnetfile.json
  jsonnet/telemeter/server/kubernetes.libsonnet
  jsonnet/telemeter/server/kubernetes/list.libsonnet
  jsonnet/telemeter/server/telemeter-server.libsonnet
  manifests/client/serviceMonitor.yaml
  manifests/prometheus/list.yaml
  manifests/server/list.yaml
  manifests/server/serviceMonitor.yaml
  manifests/server/serviceMonitorFederate.yaml
  manifests/server/statefulSet.yaml
  metrics.json
Labels: lgtm, size/L

#93 pkg/forwarder: allow no labels to be anonymized
  pkg/forwarder/forwarder.go
  pkg/forwarder/forwarder_test.go
Labels: lgtm, size/S

#95 jsonnet/telemeter: accomodate saasherder
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/lib/list.libsonnet
  jsonnet/telemeter/prometheus.libsonnet
  manifests/prometheus/list.yaml
  manifests/server/list.yaml
Labels: lgtm, size/S

#96 cmd/telemeter-server: improve rate limiting
  cmd/telemeter-server/main.go
Labels: lgtm, size/S

#97 cmd,pkg: small improvements
  cmd/telemeter-client/main.go
  pkg/forwarder/forwarder.go
Labels: lgtm, size/XS

#98 cmd/telemeter-client: add ttl, ratelimit cmdline parameters
  cmd/telemeter-client/main.go
  cmd/telemeter-server/main.go
  pkg/http/server/server.go
  pkg/metricfamily/expired.go
  pkg/store/memstore/memstore.go
  pkg/store/memstore/memstore_test.go
  test/integration.sh
Labels: lgtm, size/M
