Repository openshift/telemeter, pull requests merged in 2019-11, with the labels that each got.

#260 Add jaeger-oauth annotation on serviceaccount
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/serviceAccount.yaml
Labels: approved, lgtm, size/M

#261 jsonnet,manifests: Bump prometheus-operator to 0.34
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/jsonnetfile.json
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
Labels: approved, lgtm, size/S

#262 Metrics to collect the usage of multus cni plugin for sriov and all n…
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#263 jsonnet: Report cluster:virt_platform_nodes:sum to telemetry
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#264 The content of benchmarking.pdf does not seem PDF.
  docs/benchmarking.md
Labels: approved, lgtm, size/XS

#253 Bug 1774621: Add OLM CSV metrics
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#267 README.md: Add basic info on how to add new metrics
  README.md
Labels: approved, lgtm, size/S
