Repository openshift/telemeter, pull requests merged in 2019-02, with the labels that each got.

#125 jsonnet: fix SAR
  jsonnet/telemeter/lib/list.libsonnet
  manifests/prometheus/list.yaml
Labels: approved, lgtm, size/XS

#126 Add storage to prometheus
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
Labels: approved, lgtm, size/M

#127 jsonnet: take some values from spec
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/secret.yaml
Labels: approved, lgtm, size/M

#128 Add prometheus retention set to 15d
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
Labels: approved, lgtm, size/XS

#129 metrics: Gather the `cluster_version_available_updates` metric
  docs/data-collection.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/client/secret.yaml
  manifests/server/list.yaml
  manifests/server/secret.yaml
Labels: approved, lgtm, size/S

#131 jsonnet/telemeter/server: move whitelist out of secret
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/secret.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/M
