Repository openshift/telemeter, pull requests merged in 2019-12, with the labels that each got.

#266 Bug 1773246: Report cluster:virt_platform_nodes:sum to telemetry
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#251 insightsclient_request_send_total metric from insights-operator
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#268 jsonnet: Whitelist cluster:usage:* for telemetry
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#270 Bug 1779913: Add a whitelist cluster:usage:* for telemetry for simple usage metric exposure
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#272 test/e2e: fix forward test
  Makefile
  test/e2e/forward_test.go
Labels: approved, lgtm, size/S

#273 cmd/telemeter-server,pkg/cache: cache auth resps
  Makefile
  cmd/telemeter-server/main.go
  go.mod
  go.sum
  jsonnet/server.jsonnet
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
  pkg/authorize/handler.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/cache/cache.go
  pkg/cache/memcached/memcached.go
  test/integration-v2.sh
  test/integration.sh
  vendor/github.com/bradfitz/gomemcache/LICENSE
  vendor/github.com/bradfitz/gomemcache/memcache/memcache.go
  vendor/github.com/bradfitz/gomemcache/memcache/selector.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#274 pkg/cluster: fix running telemeter without verbose
  pkg/cluster/memberlist.go
Labels: approved, lgtm, size/XS

#275 OWNERS: add bartek
  OWNERS
Labels: approved, lgtm, size/XS

#276 jsonnet/telemeter: fix memcached replica offset
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm, size/XS

#278 pkg/cache: update memcached dns on interval
  cmd/telemeter-server/main.go
  pkg/cache/memcached/memcached.go
Labels: approved, lgtm, size/M

#280 jsonnet/telemeter: monitor memcached
  jsonnet/telemeter/lib/list.libsonnet
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm, size/L

#282 pkg/authorize: Print body on unexpected authz request result
  pkg/authorize/handler.go
Labels: approved, lgtm, size/XS

#283 jsonnet/telemeter: ensure tag in memcached
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm, size/XS

#284 jsonnet/telemeter: fix setMemcached func
  jsonnet/telemeter/lib/list.libsonnet
Labels: approved, lgtm, size/S

#281 Bug 1773665: Backport changes from BZ 1760393 to 4.2.z
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#277 Enforce forwarding from v1 /upload to v2 receive hashring
  pkg/store/forward/forward.go
Labels: approved, lgtm, size/L

#286 Add first Telemeter recording rules
  docs/data-collection.md
  jsonnet/telemeter/metrics.jsonnet
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, size/M
