Repository openshift/telemeter, pull requests merged in 2019-08, with the labels that each got.

#208 OBS-17: implement client credentials grant flow
  cmd/telemeter-server/main.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#209 jsonnet: Include workload:*:sum metrics in reporting
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/M

#210 Bug 1737164: Add OLM metrics to whitelist
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#212 metrics: gather cluster_installer series
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
  test/timeseries.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#211 Bug 1732945: Capture cluster infrastructure metrics
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#214 Log the mean drift from current timestamp when forward fails
  pkg/store/forward/forward.go
  pkg/store/forward/forward_test.go
Labels: approved, lgtm, size/M

#215 expose node_uname_info metric
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  test/timeseries.txt
Labels: approved, lgtm, size/S

#217 Log mean drift time for cluster more than 10s apart
  pkg/store/forward/forward.go
Labels: approved, lgtm, size/XS

#213 pkg/store/forward: defensively override timestamps
  pkg/store/forward/forward.go
  pkg/store/forward/forward_test.go
Labels: approved, lgtm, size/M

#218 pkg/store/forward: only overwrite future timestamps
  pkg/store/forward/forward.go
Labels: approved, lgtm, size/S

#219 pkg/store/forward: add tenant header
  pkg/store/forward/forward.go
Labels: approved, lgtm, size/XS

#220 jsonnet/telemeter: remove auth username
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm, size/XS

#201 Added metrics list for NooBaa under OCS
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  test/timeseries.txt
Labels: approved, lgtm, ok-to-test, size/M

#222 Bug 1732945: Cherry pick 205 to 4.1 branch
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#221 Bug 1732945: jsonnet/telemeter/jsonnetfile.json: Adjust syncs
  jsonnet/telemeter/jsonnetfile.json
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#224 cmd,jsonnet: rename oidc flags
  cmd/telemeter-server/main.go
  jsonnet/telemeter/server/kubernetes.libsonnet
  pkg/oauth2/token_source.go
  pkg/oauth2/token_source_test.go
Labels: approved, lgtm, size/XL

#48 deploy: remove deploy directory
  deploy/authorization-server.yaml
  deploy/default-rules
  deploy/prometheus.yaml
  deploy/telemeter-client-openshift.yaml
  deploy/telemeter-client.yaml
  deploy/telemeter-server.yaml
  deploy/telemeter.secret.yaml
  test/integration.sh
Labels: approved, lgtm, size/L

#226 Bug 1744017: pkg/forwarder: dont proxy in-cluster requests
  pkg/benchmark/benchmark.go
  pkg/forwarder/forwarder.go
  pkg/metricsclient/metricsclient.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#223 Add a receive handler to Telemeter for remote-write
  cmd/telemeter-server/main.go
  pkg/authorize/client.go
  pkg/authorize/context.go
  pkg/authorize/handler.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/receive/handler.go
Labels: approved, lgtm, size/L

#227 jsonnet: simplify benchmark conifg
  jsonnet/telemeter/benchmark/kubernetes.libsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/benchmark/statefulSetTelemeterServer.yaml
Labels: approved, lgtm, size/M

#229 Bug 1746686: jsonnet: fix client reload port
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S
