Repository openshift/telemeter, pull requests merged in 2019-05, with the labels that each got.

#167 jsonnet: add nodeSelector to telemeter client
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/XS

#168 pkg/metricsclient: fix data race when creating error message while closing context
  Makefile
  pkg/metricsclient/metricsclient.go
Labels: approved, lgtm, size/S

#169 Bug 1707681: pkg/forwarder: fix ever growing URI
  pkg/forwarder/forwarder.go
Labels: approved, lgtm, size/XS

#170 jsonnet/telemeter/prometheus: remove route declaration
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/route.yaml
Labels: approved, lgtm, size/M

#173 Bump Prometheus Operator to v0.30.0 in jsonnet
  jsonnet/telemeter/jsonnetfile.json
Labels: approved, lgtm, size/XS

#176 Add Travis config and use containerized jsonnet
  .gitignore
  .travis.yml
  Makefile
Labels: approved, lgtm, size/L

#177 *: move to prow and remove travis
  .travis.yml
Labels: approved, lgtm, size/S
