Repository openshift/telemeter, pull requests merged in 2019-04, with the labels that each got.

#150 pkg/authorize/tollbooth: handle 404 - cluster not found
  pkg/authorize/tollbooth/tollbooth.go
Labels: approved, lgtm, size/XS

#152 authorize/jwt/handler: log authorize failures for >= 500
  pkg/authorize/jwt/handler.go
Labels: approved, lgtm, size/XS

#149 Add resource limits to telemeter server and prometheus
  jsonnet/telemeter/lib/list.libsonnet
  jsonnet/telemeter/prometheus.libsonnet
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/L

#154 Makefile: fix install of go-jsonnet
  Makefile
Labels: approved, lgtm, size/XS

#153 jsonnet: prometheus route balance source IP
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/route.yaml
Labels: approved, lgtm, size/XS

#157 client: Set priority class
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/XS

#158 Update server & prometheus templates default resources
  jsonnet/telemeter/lib/list.libsonnet
  manifests/server/list.yaml
Labels: approved, lgtm, size/S

#159 Makefile,docs: show how to run query in prometheus
  .gitignore
  Makefile
  docs/sample-metrics.md
  test/timeseries.txt
Labels: approved, lgtm, size/XXL

#160 docs/sample-metrics: fix formatting
  docs/sample-metrics.md
Labels: approved, lgtm, size/XS

#161 metrics.jsonnet: remove old metrics
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/S

#156 Remove two major sources of contention from telemeter
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/http/routes.go
  pkg/store/ratelimited/ratelimited.go
Labels: approved, lgtm, size/M

#162 metrics.json: reduce etcd object counts
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/M

#165 test: update time series
  Makefile
  docs/sample-metrics.md
  test/timeseries.txt
Labels: approved, lgtm, size/XXL
