Repository openshift/telemeter, pull requests merged in 2019-07, with the labels that each got.

#190 Honor labels in telemeter prometheus
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/serviceMonitor.yaml
Labels: approved, lgtm, size/XS

#196 Remove Telemeter server manifests from this repository
  Makefile
  manifests/server/list.yaml
  manifests/server/secret.yaml
  manifests/server/service.yaml
  manifests/server/serviceAccount.yaml
  manifests/server/serviceMonitor.yaml
  manifests/server/serviceMonitorFederate.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/L

#189 metrics: gather cluster_installer series
  Makefile
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  test/timeseries.txt
Labels: approved, lgtm, size/XL

#197 metrics: Remove telemetry metrics for image registry and etcd
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#198 metrics: Remove a metric that is no longer reported
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#194 metrics: add metrics list for CNV
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#202 jsonnet: disable htpasswd auth in prometheus proxy
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/htpasswdSecret.yaml
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
Labels: approved, lgtm, size/M

#195 Add OLM metrics to whitelist
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#200 Add support for HTTP proxy env vars
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#199 test/benchmark: test goal
  Makefile
  test/benchmark.sh
Labels: approved, lgtm, size/M

#203 test/benchmark: cut down flakes and speed up test
  Makefile
  test/benchmark.sh
Labels: approved, lgtm, size/S

#204 Add Route annotation to ServiceAccount for thanos-querier
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/serviceAccount.yaml
Labels: approved, lgtm, size/XS

#205 Bug 1731232,1731228: Capture cluster infrastructure metrics
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#206 jsonnet: change benchmark crb name
  jsonnet/telemeter/benchmark.libsonnet
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
Labels: approved, lgtm, size/XS

#192 Added metrics list for OCS
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/M

#207 Increase token store authorizer timeout to 30s
  pkg/authorize/token_store.go
Labels: approved, lgtm, size/XS
