Repository openshift/telemeter, pull requests merged in 2019-09, with the labels that each got.

#231 Bump prometheus-operator to 0.32
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/jsonnetfile.json
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
Labels: approved, lgtm, size/S

#232 Add metalmatze to the list of OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#233 Add Oauth reference to prometheus telemeter SA
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/serviceAccount.yaml
Labels: approved, lgtm, size/XS

#236 Remove riuvshin from owners
  OWNERS
Labels: approved, lgtm, size/XS

#235 Bug 1749451: Capture sum of cpu capacity cores by OS (RHCOS or RHEL), arch, and role for the nodes.
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/S

#238 Overwrite all timestamps for Telemeter v1 & v2
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  pkg/http/server/server.go
  pkg/http/server/server_test.go
  pkg/metricfamily/overwrite.go
  pkg/store/forward/forward.go
  pkg/validate/validator.go
  test/e2e/forward_test.go
Labels: approved, lgtm, size/M

#239 Add metrics gathering for console_url
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/XS

#240 OWNERS: Add lilic
  OWNERS
Labels: approved, lgtm, size/XS

#242 telemeter-server: Fix receive path
  cmd/telemeter-server/main.go
Labels: approved, lgtm, size/XS

#243 pkg/authorize: decode token from base64
  pkg/authorize/handler.go
  pkg/authorize/tollbooth/tollbooth.go
Labels: approved, lgtm, size/S

#244 OWNERS: Add kakkoyun
  OWNERS
Labels: approved, lgtm, size/XS

#237 Add structured logging
  .errcheck_excludes.txt
  .golangci.yml
  Makefile
  cmd/authorization-server/main.go
  cmd/telemeter-benchmark/main.go
  cmd/telemeter-client/main.go
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_test.go
  go.mod
  pkg/authorize/handler.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/jwt/handler_test.go
  pkg/authorize/jwt/validator.go
  pkg/authorize/tollbooth/mock.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/benchmark/benchmark.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/memberlist.go
  pkg/forwarder/forwarder.go
  pkg/forwarder/forwarder_test.go
  pkg/http/roundtripper.go
  pkg/http/server/server.go
  pkg/logger/logger.go
  pkg/metricsclient/metricsclient.go
  pkg/receive/handler.go
  pkg/store/forward/forward.go
  test/e2e/forward_test.go
Labels: approved, lgtm, size/XL
