Repository openshift/telemeter, pull requests merged in 2019-03, with the labels that each got.

#133 jsonnet: fix argument quoting
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/M

#134 Add SRE team to OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#135 cmd/telemeter-server: instrument http clients
  cmd/telemeter-server/main.go
  pkg/http/client.go
  pkg/http/server.go
Labels: approved, lgtm, size/L

#136 added SLI metrics for openshift-sre
  docs/data-collection.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/client/secret.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/M

#138 add metrics, use correct metric type in store
  pkg/store/instrumented/instrumented.go
  pkg/store/memstore/memstore.go
Labels: approved, lgtm, size/M

#139 cmd/telemeter-server: start memory store cleaner
  cmd/telemeter-server/main.go
Labels: approved, lgtm, size/XS

#140 pkg/store: consolidate metrics
  cmd/telemeter-server/main.go
  pkg/http/server/server.go
  pkg/store/instrumented/instrumented.go
  pkg/store/memstore/memstore.go
Labels: approved, lgtm, size/L

#142 jsonnet/telemeter: Pin Prometheus Operator version
  jsonnet/telemeter/jsonnetfile.json
Labels: approved, lgtm, size/XS

#144 jsonnet/telemeter/client: move metrics from secret
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/secret.yaml
Labels: approved, lgtm, size/S

#143 jsonnet/telemeter: add infrastructure metrics
  docs/data-collection.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/M

#145 jsonnet: add session affinity to prom svc
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/service.yaml
Labels: approved, lgtm, size/XS

#146 pkg/metricfamily: add elide transformer
  cmd/telemeter-server/main.go
  pkg/metricfamily/elide.go
  pkg/metricfamily/elide_test.go
  test/integration.sh
  test/prom-local.conf
Labels: approved, lgtm, size/L

#147 jsonnet/telemeter: elide prometheus_replica label
  jsonnet/telemeter/server.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, lgtm, size/S

#148 pkg/forwarder: fix match flag
  pkg/forwarder/forwarder.go
Labels: approved, lgtm, size/XS
