Repository openshift/telemeter, pull requests merged in 2019-10, with the labels that each got.

#246 jsonnet/: Use local directory
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm, size/S

#250 cmd: add limit-bytes flag
  cmd/telemeter-client/main.go
  cmd/telemeter-server/main.go
Labels: approved, lgtm, size/XS

#245 Bug 1746711: fix client reload port
  Makefile
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#252 Bug 1750283: Backport bug 1749451 for whitelisting of cpu core node role metric.
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/secretTelemeterServer.yaml
  manifests/client/deployment.yaml
  manifests/server/list.yaml
  manifests/server/statefulSet.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/S

#254 Added rrati to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#255 Bug 1760393:Add node_role_os_version_machine:cpu_capacity_sockets:sum metric to telemeter whitelist.
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/S

#256 metrics: gather cluster_control_plane_architecture
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#258 Revert "metrics: gather cluster_control_plane_architecture"
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S
