Repository openshift/telemeter, pull requests merged in 2019-06, with the labels that each got.

#181 *: download build binaries without using go modules
  Makefile
Labels: approved, lgtm, size/S

#179 pkg/store/ratelimited: log offending key
  pkg/http/server/server.go
  pkg/store/ratelimited/ratelimited.go
  pkg/store/ratelimited/ratelimited_test.go
Labels: approved, lgtm, size/S

#182 pkg/oauth2: consider session cancellation
  cmd/telemeter-server/main.go
  pkg/oauth2/token_source.go
  pkg/oauth2/token_source_test.go
Labels: approved, lgtm, size/L

#183 jsonnet: Bump prometheus-operator
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/jsonnetfile.json
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
Labels: approved, lgtm, size/S

#184 Makefile: unblock golangci-lint installation
  Makefile
Labels: approved, lgtm, size/XS

#185 Update ownership
  OWNERS
Labels: approved, lgtm, size/XS

#186 pkg/store: fix ratelimited err overflow
  pkg/store/ratelimited/ratelimited.go
Labels: approved, lgtm, size/XS

#187 Bump prometheus operator
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/jsonnetfile.json
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
Labels: approved, lgtm, size/M
