Repository openshift/telemeter, pull requests merged in 2020-03, with the labels that each got.

#313 Move benchmark to remote write
  Makefile
  jsonnet/benchmark.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/benchmark.libsonnet
  jsonnet/telemeter/benchmark/kubernetes.libsonnet
  manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
  manifests/benchmark/configmapThanosReceiveController.yaml
  manifests/benchmark/deploymentPrometheusOperator.yaml
  manifests/benchmark/deploymentThanosQuery.yaml
  manifests/benchmark/deploymentThanosReceiveController.yaml
  manifests/benchmark/prometheusPrometheus.yaml
  manifests/benchmark/roleBindingConfigPrometheus.yaml
  manifests/benchmark/roleBindingSpecificNamespacesPrometheus.yaml
  manifests/benchmark/roleBindingThanosReceiveController.yaml
  manifests/benchmark/roleConfigPrometheus.yaml
  manifests/benchmark/roleSpecificNamespacesPrometheus.yaml
  manifests/benchmark/roleThanosReceiveController.yaml
  manifests/benchmark/routePrometheus.yaml
  manifests/benchmark/routeThanosQuery.yaml
  manifests/benchmark/rulesPrometheus.yaml
  manifests/benchmark/serviceAccountPrometheus.yaml
  manifests/benchmark/serviceAccountPrometheusOperator.yaml
  manifests/benchmark/serviceAccountThanosReceiveController.yaml
  manifests/benchmark/serviceMonitorFederateTelemeterServer.yaml
  manifests/benchmark/serviceMonitorTelemeterServer.yaml
  manifests/benchmark/servicePrometheus.yaml
  manifests/benchmark/serviceThanosQuery.yaml
  manifests/benchmark/serviceThanosReceiveController.yaml
  manifests/benchmark/serviceThanosReceivedefault.yaml
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/benchmark/statefulSetThanosReceivedefault.yaml
  test/benchmark.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#316 jsonnet: remove prometheus operator
  jsonnet/jsonnetfile.lock.json
  jsonnet/telemeter/jsonnetfile.json
Labels: approved, lgtm, size/S

#315 test/integration: fix already used port race
  test/integration-v2.sh
Labels: approved, lgtm, size/S

#318 jsonnet/telemeter: remove prometheus
  Makefile
  jsonnet/prometheus.jsonnet
  jsonnet/telemeter/lib/list.libsonnet
  jsonnet/telemeter/prometheus.libsonnet
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/prometheus/clusterRole.yaml
  manifests/prometheus/clusterRoleBinding.yaml
  manifests/prometheus/list.yaml
  manifests/prometheus/prometheus.yaml
  manifests/prometheus/proxySecret.yaml
  manifests/prometheus/roleBindingConfig.yaml
  manifests/prometheus/roleBindingSpecificNamespaces.yaml
  manifests/prometheus/roleConfig.yaml
  manifests/prometheus/roleSpecificNamespaces.yaml
  manifests/prometheus/rules.yaml
  manifests/prometheus/service.yaml
  manifests/prometheus/serviceAccount.yaml
  manifests/prometheus/serviceMonitor.yaml
Labels: approved, lgtm, size/XL

#319 Bug 1812719: jsonnet/telemeter: set cpu requests, unset limits
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#279 Receive requests are required to have partitionKey label
  cmd/telemeter-server/main.go
  pkg/receive/handler.go
  test/e2e/forward_test.go
  test/e2e/receive_test.go
Labels: approved, lgtm, size/M

#321 Move all routes and handlers into scoped blocks
  cmd/telemeter-server/main.go
Labels: approved, lgtm

#322 jsonnet: Ensure env var is actually added
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm

#320 Bug 1813221: jsonnet/telemeter: set cpu requests, unset limits
  Makefile
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm
