Repository openshift/telemeter, pull requests merged in 2020-02, with the labels that each got.

#306 BUG 1796927: *: Move metrics whitelist to downstream usage
  README.md
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/benchmark.libsonnet
  jsonnet/telemeter/client.libsonnet
  jsonnet/telemeter/metrics.jsonnet
  jsonnet/telemeter/server.libsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
  metrics.json
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#309 Bug 1805116: jsonnet/telemeter/metrics: add aggregated up metric, remove node_uname_info
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#312 jsonnet/benchmark: ensure benchmark has metrics
  Makefile
  jsonnet/benchmark.jsonnet
  jsonnet/telemeter/benchmark.libsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
Labels: approved, lgtm, size/M
