Repository openshift/telemeter, pull requests merged in 2020-01, with the labels that each got.

#289 jsonnet: use stable APIS in benchmark manifests
  jsonnet/telemeter/benchmark/kubernetes.libsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
Labels: approved, lgtm, size/S

#287 Dockerfile: update to Go 1.13
  Dockerfile
Labels: approved, lgtm, size/XS

#294 test: Use specific version of UP to fix broken integration tests
  Makefile
Labels: approved, lgtm, size/XS

#291 OWNERS: add rporres
  OWNERS
Labels: approved, lgtm, size/XS

#292 test: use UP for querying in integration test
  Makefile
  go.mod
  go.sum
  test/integration-v2.sh
  test/integration.sh
  vendor/github.com/observatorium/up/.drone.yml
  vendor/github.com/observatorium/up/.errcheck_excludes
  vendor/github.com/observatorium/up/.gitignore
  vendor/github.com/observatorium/up/.golangci.yml
  vendor/github.com/observatorium/up/Makefile
  vendor/github.com/observatorium/up/README.md
  vendor/github.com/observatorium/up/go.mod
  vendor/github.com/observatorium/up/main.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#288 Consume authorize_url from Secret
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, lgtm, size/XS

#296 jsonnet/telemeter: Add recording rule for cluster availability
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, size/XS

#299 pkg/receive: return correct status code
  pkg/receive/handler.go
Labels: approved, lgtm, size/XS

#297 jsonnet/telemeter: Record a "subscribed cluster" metric
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, size/S

#298 Capture total CAM app workload migrations by migration state.
  docs/data-collection.md
  docs/sample-metrics.md
  jsonnet/telemeter/metrics.jsonnet
  manifests/benchmark/statefulSetTelemeterServer.yaml
  manifests/client/deployment.yaml
Labels: approved, lgtm, size/S

#301 dockerfiles: simplify app-sre build tooling
  build_deploy.sh
  dockerfiles/Dockerfile.build
  dockerfiles/Dockerfile.deploy
  dockerfiles/README.txt
Labels: approved, lgtm, size/S

#300 Fix remote write metrics
  cmd/telemeter-server/main.go
  pkg/receive/handler.go
  pkg/store/forward/forward.go
Labels: approved, lgtm, size/M

#302 Makefile: execute built `jb` from correct path
  Makefile
Labels: approved, lgtm, size/XS

#305 Add annotation for new Observatorium API Route
  jsonnet/telemeter/prometheus/kubernetes.libsonnet
  manifests/prometheus/list.yaml
  manifests/prometheus/serviceAccount.yaml
Labels: approved, lgtm, size/XS
