Repository openshift/telemeter, pull requests merged in 2020-05, with the labels that each got.

#331 Handle Entity too large errors separately
  pkg/server/snappy.go
  pkg/server/validator.go
Labels: approved

#330 Fix Validator marshal error
  pkg/server/validator.go
Labels: approved, lgtm

#332 telemeter-server: Always set OpenShift telemetry tenant ID
  pkg/receive/handler.go
  pkg/server/forward.go
Labels: approved, lgtm

#333 telemeter-server: Make downstream tenant ID configurable
  cmd/telemeter-server/main.go
  pkg/receive/handler.go
  pkg/server/forward.go
  test/e2e/forward_test.go
  test/e2e/receive_test.go
Labels: approved, lgtm

#334 Bug 1813894: Stop using service ca from service account token
  jsonnet/telemeter/server/kubernetes.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#335 jsonnet: Upgrade apps API versions used to apps/v1
  jsonnet/telemeter/client/kubernetes.libsonnet
  jsonnet/telemeter/server/kubernetes.libsonnet
  manifests/client/deployment.yaml
Labels: approved, lgtm
