Repository openshift/telemeter, pull requests merged in 2020-09, with the labels that each got.

#349 Bug 1873428: Fixed mem-leak and added proper e2e that uses prod code.
  cmd/telemeter-server/main.go
  cmd/telemeter-server/main_e2e_test.go
  go.mod
  go.sum
  pkg/authorize/stub/stub.go
  pkg/http/client.go
  pkg/runutil/runutil.go
  pkg/runutil/runutil_test.go
  pkg/server/forward.go
  pkg/server/validator.go
  test/e2e/forward_test.go
  test/e2e/receive_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.travis.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/glide.yaml
  vendor/go.uber.org/goleak/go.mod
  vendor/go.uber.org/goleak/go.sum
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tools.go
  vendor/golang.org/x/lint/.travis.yml
  vendor/golang.org/x/lint/CONTRIBUTING.md
  vendor/golang.org/x/lint/LICENSE
  vendor/golang.org/x/lint/README.md
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/lint/golint/golint.go
  vendor/golang.org/x/lint/golint/import.go
  vendor/golang.org/x/lint/golint/importcomment.go
  vendor/golang.org/x/lint/lint.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/LICENSE
  vendor/golang.org/x/tools/PATENTS
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/gcexportdata/importer.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/exportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface10.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface11.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#355 Bug 1874112: Do not overwrite 3xx and 4xx from Tollbooth to 500
  pkg/authorize/handler.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#351 Bug 1874389: add Ari to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#356 Bug 1877816: Provide synthetic recording rules for common cluster id -> key dimensional joins
  jsonnet/telemeter/rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#357 Bug 1879009: jsonnet/telemeter: Fix cluster_subscribed recording rule
  jsonnet/telemeter/rules.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#358 Bug 1879965: jsonnet/telemeter: Use `host_type` in recording rule join
  jsonnet/telemeter/rules.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
