Repository openshift/telemeter, pull requests merged in 2022-08, with the labels that each got.

#420 Bump Telemeter rules evaluation interval to 4m
  jsonnet/telemeter/rules.libsonnet
Labels: approved, needs-ok-to-test, lgtm

#422 pkg/server: use v1 forward requests counter
  pkg/server/forward.go
Labels: approved, lgtm, ok-to-test

#424 OWNERS: Add myself, and move former team members to emeritus
  OWNERS
Labels: approved, lgtm

#423 pkg/receive/handler: Propagate upstream error message
  pkg/receive/handler.go
Labels: approved, lgtm, ok-to-test

#426 pkg/receive/handler: Use OIDC client
  cmd/telemeter-server/main.go
  pkg/receive/handler.go
  test/e2e/receive_test.go
Labels: approved, lgtm, ok-to-test

#425 OWNERS: Add myself to owners file
  OWNERS
Labels: approved, needs-ok-to-test, lgtm

#427 pkg/receive/handler: Add middleware to respect whitelist + elide
  cmd/telemeter-server/main.go
  pkg/receive/handler.go
  test/e2e/receive_test.go
Labels: approved, lgtm

#429 Forward: Add logic to sanitize labels
  cmd/telemeter-server/main_e2e_test.go
  pkg/server/forward.go
  pkg/server/forward_test.go
Labels: approved, lgtm
