Repository openshift/telemeter, pull requests merged in 2023-06, with the labels that each got.

#464 OCPBUGS-12345: tools: update to golangci-lint v1.51
  .ci-operator.yaml
  Dockerfile
  Makefile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#466 Fix path benchmark
  Makefile
Labels: approved, lgtm

#461 Fix integration test documentation
  README.md
  test/integration.sh
Labels: approved, lgtm

#467 Improve debug roundtripper logs
  pkg/http/roundtripper.go
Labels: approved, lgtm

#468 jsonnet: Add config to support rhelemeter
  jsonnet/telemeter/rhelemeter.libsonnet
  jsonnet/telemeter/server/rhelemeter-kubernetes.libsonnet
Labels: approved, lgtm

#455 MON-3230: Add TLS auth to telemeter-client
  cmd/telemeter-client/main.go
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/service.yaml
  pkg/forwarder/forwarder.go
Labels: approved, lgtm, jira/valid-reference

#470 [rhelemeter]: add secret for external mtls connection
  jsonnet/telemeter/server/rhelemeter-kubernetes.libsonnet
Labels: approved, lgtm

#472 Revert wrong cert name change of #455
  jsonnet/telemeter/client/kubernetes.libsonnet
  manifests/client/deployment.yaml
  manifests/client/service.yaml
Labels: approved, lgtm

#473 [rhelemeter]: fix mtls secret generation
  jsonnet/telemeter/rhelemeter.libsonnet
  jsonnet/telemeter/server/rhelemeter-kubernetes.libsonnet
Labels: approved, lgtm
