Repository openshift/telemeter, pull requests merged in 2023-02, with the labels that each got.

#449 server: Ensure logging level is flag is respected
  cmd/telemeter-server/main.go
Labels: approved, lgtm

#447 OCPBUGS-6962: Add 'agent-installer' value to 'install_type' label
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#451 OCPBUGS-7702: Add 'agent-installer' value to 'install_type' label
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
