Repository openshift/telemeter, pull requests merged in 2024-02, with the labels that each got.

#504 OCPBUGS-16397: update nutanix filter
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#505 MON-3669: fix join issue in cluster:capacity_effective_cpu_cores
  jsonnet/telemeter/rules.libsonnet
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#509 MON-3708: fix test/integration.sh
  Makefile
  test/integration.sh
  test/prom-local-alerts.yaml
  test/prom-local.yaml
Labels: approved, lgtm, jira/valid-reference

#506 RHOBS-995: Simplify cluster:capacity_effective_cpu_cores, add tests
  Makefile
  README.md
  jsonnet/telemeter/rules.libsonnet
  test/rulestests.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#513 MON-3715: remove obsolete targets from Makefile
  .gitignore
  Makefile
  tools/go.mod
  tools/tools.go
Labels: approved, lgtm, jira/valid-reference

#512 MON-3175: README.md: update deprecated link
  README.md
Labels: approved, lgtm, jira/valid-reference
