Repository openshift/telemeter, pull requests merged in 2024-06, with the labels that each got.

#536 OCPBUGS-34833: fix issuer check during JWT authentication
  pkg/authorize/jwt/client_authorizer.go
  pkg/authorize/jwt/client_authorizer_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#534 MON-3890: add recording rule acm_capacity_effective_cpu_cores
  jsonnet/telemeter/rules.libsonnet
  test/rulestests.yaml
Labels: approved, lgtm, jira/valid-reference

#538 OCPBUGS-34831: fix issuer check during JWT authentication for 4.15
  pkg/authorize/jwt/client_authorizer.go
  pkg/authorize/jwt/client_authorizer_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#539 OCPBUGS-34830: fix issuer check during JWT authentication 4.14
  cmd/telemeter-server/main.go
  pkg/authorize/client.go
  pkg/authorize/handler.go
  pkg/authorize/jwt/client_authorizer.go
  pkg/authorize/jwt/client_authorizer_test.go
  pkg/authorize/jwt/handler.go
  pkg/authorize/tollbooth/tollbooth.go
  pkg/cache/cache.go
  pkg/receive/handler.go
  pkg/server/ratelimited.go
  pkg/server/requestlog.go
  pkg/server/validator.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
